/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.views;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.CollectionFormController;
import lk.ijse.pos.dto.CollectionDTO;
import lk.ijse.pos.entity.Collection;

/**
 *
 * @author Yashitha Nadiranga
 */
public class CollectionForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form HomeForm
     */
    public CollectionForm() {
        initComponents();
        setUI();
        loadAllData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCollection = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFoodName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFoodPrice = new javax.swing.JTextField();
        btnDelete = new keeptoo.KButton();
        btnSave = new keeptoo.KButton();
        btnClear = new keeptoo.KButton();
        btnUpdate = new keeptoo.KButton();
        txtFoodId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(990, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCollection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblCollection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food ID", "Food Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCollection.setSelectionBackground(new java.awt.Color(50, 51, 53));
        tblCollection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCollectionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCollection);
        if (tblCollection.getColumnModel().getColumnCount() > 0) {
            tblCollection.getColumnModel().getColumn(0).setResizable(false);
            tblCollection.getColumnModel().getColumn(1).setResizable(false);
            tblCollection.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 950, 320));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setText("Food Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtFoodName.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtFoodName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(184, 14, 61)));
        jPanel1.add(txtFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 310, -1));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel3.setText("Food ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtSearch.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(184, 14, 61)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 300, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel4.setText("Search Food");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        txtFoodPrice.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtFoodPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(184, 14, 61)));
        jPanel1.add(txtFoodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 310, -1));

        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setkAllowGradient(false);
        btnDelete.setkBackGroundColor(new java.awt.Color(221, 48, 48));
        btnDelete.setkHoverColor(new java.awt.Color(221, 15, 48));
        btnDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDelete.setkHoverStartColor(new java.awt.Color(30, 133, 242));
        btnDelete.setkPressedColor(new java.awt.Color(221, 48, 48));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSave.setkAllowGradient(false);
        btnSave.setkBackGroundColor(new java.awt.Color(33, 150, 83));
        btnSave.setkHoverColor(new java.awt.Color(38, 137, 66));
        btnSave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSave.setkHoverStartColor(new java.awt.Color(30, 133, 242));
        btnSave.setkPressedColor(new java.awt.Color(33, 150, 83));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(24, 133, 242));
        btnClear.setkHoverColor(new java.awt.Color(0, 98, 204));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnClear.setkHoverStartColor(new java.awt.Color(30, 133, 242));
        btnClear.setkPressedColor(new java.awt.Color(24, 133, 242));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setkAllowGradient(false);
        btnUpdate.setkBackGroundColor(new java.awt.Color(255, 215, 71));
        btnUpdate.setkHoverColor(new java.awt.Color(255, 231, 71));
        btnUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate.setkHoverStartColor(new java.awt.Color(30, 133, 242));
        btnUpdate.setkPressedColor(new java.awt.Color(255, 215, 71));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        txtFoodId.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtFoodId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(184, 14, 61)));
        jPanel1.add(txtFoodId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 310, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel5.setText("Food Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        sendData();
        loadAllData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateData();
        loadAllData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteData();
        loadAllData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        searchData();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblCollectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCollectionMouseClicked
        int r = tblCollection.getSelectedRow();
        String id = tblCollection.getValueAt(r, 0).toString();
        String name = tblCollection.getValueAt(r, 1).toString();
        String price = tblCollection.getValueAt(r, 2).toString();
        txtFoodId.setText(id);
        txtFoodName.setText(name);
        txtFoodPrice.setText(price);
    }//GEN-LAST:event_tblCollectionMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtFoodId.setText("");
        txtFoodName.setText("");
        txtFoodPrice.setText("");
        txtSearch.setText("");
        loadAllData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void setUI() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        tblCollection.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblCollection.getTableHeader().setOpaque(false);
        tblCollection.getTableHeader().setBackground(new Color(184, 14, 61));
        tblCollection.getTableHeader().setForeground(new Color(255, 255, 255));
        tblCollection.getTableHeader().setBorder(new LineBorder(Color.white));
        tblCollection.setRowHeight(30);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        
        Color ivory = new Color(255, 255, 255);
        tblCollection.setOpaque(true);
        tblCollection.setFillsViewportHeight(true);
        tblCollection.setBackground(ivory);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnSave;
    private keeptoo.KButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCollection;
    private javax.swing.JTextField txtFoodId;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtFoodPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void sendData() {
        
        try {
            CollectionDTO c1 = new CollectionDTO(
                    txtFoodId.getText(),
                    txtFoodName.getText(),
                    txtFoodPrice.getText()
            );
            
            if(new CollectionFormController().uploadData(c1)){
                JOptionPane.showMessageDialog(this, "Data Saved Successfully!");
            }else{
                JOptionPane.showMessageDialog(this, "Something went wrong!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    private void updateData() {
        try {
            CollectionDTO c1 = new CollectionDTO(
                    txtFoodId.getText(),
                    txtFoodName.getText(),
                    txtFoodPrice.getText()
            );
            
            
            if(new CollectionFormController().updateData(c1)){
                JOptionPane.showMessageDialog(this, "Data updated Successfully!");
            }else{
                JOptionPane.showMessageDialog(this, "Something went wrong!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void deleteData() {
        try {
            String fid = txtFoodId.getText();
            
            if(new CollectionFormController().DeleteData(fid)){
                JOptionPane.showMessageDialog(this, "Data Deleted Successfully!");
            }else{
                JOptionPane.showMessageDialog(this, "Something went wrong!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllData() {
        try {
            List<CollectionDTO> list = new CollectionFormController().getAll();
            DefaultTableModel model = (DefaultTableModel) tblCollection.getModel();
            model.setRowCount(0);
            for (CollectionDTO collectionDTO : list) {
                model.addRow(new Object[]{collectionDTO.getFid(),collectionDTO.getFname(),collectionDTO.getFprice()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchData() {
        try {
            String s = txtSearch.getText();
            List <CollectionDTO>list = new CollectionFormController().getSearch(s);
            DefaultTableModel model = (DefaultTableModel) tblCollection.getModel();
            model.setRowCount(0);
            for (CollectionDTO collectionDTO : list) {
                model.addRow(new Object[]{collectionDTO.getFid(),collectionDTO.getFname(),collectionDTO.getFprice()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CollectionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
}
