/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.views;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.HomeFormController;
import lk.ijse.pos.dto.OrdersDTO;

/**
 *
 * @author Yashitha Nadiranga
 */
public class HomeForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
        setUI();
        loadOrders();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHome = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(990, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Pickup Date & Time", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHome.setSelectionBackground(new java.awt.Color(50, 51, 53));
        tblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHomeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHome);
        if (tblHome.getColumnModel().getColumnCount() > 0) {
            tblHome.getColumnModel().getColumn(0).setResizable(false);
            tblHome.getColumnModel().getColumn(1).setResizable(false);
            tblHome.getColumnModel().getColumn(2).setResizable(false);
            tblHome.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, 950, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHomeMouseClicked
        int row = tblHome.getSelectedRow();
        String oid = tblHome.getValueAt(row, 0).toString();
        
//        if (!oid.equals(null)) {
            new UpdateForm(new javax.swing.JFrame(), true,oid,this).setVisible(true);
//        }
    }//GEN-LAST:event_tblHomeMouseClicked

    private void setUI() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        tblHome.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblHome.getTableHeader().setOpaque(false);
        tblHome.getTableHeader().setBackground(new Color(184, 14, 61));
        tblHome.getTableHeader().setForeground(new Color(255, 255, 255));
        tblHome.getTableHeader().setBorder(new LineBorder(Color.white));
        tblHome.setRowHeight(30);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        
        Color ivory = new Color(255, 255, 255);
        tblHome.setOpaque(true);
        tblHome.setFillsViewportHeight(true);
        tblHome.setBackground(ivory);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHome;
    // End of variables declaration//GEN-END:variables

    public void loadOrders() {
        try {
            ArrayList<OrdersDTO> list = new HomeFormController().getOrders();

            DefaultTableModel model = (DefaultTableModel) tblHome.getModel();
            model.setRowCount(0);

            for (OrdersDTO o : list) {
                if (o.getStatus().equalsIgnoreCase("Processing")) {
                    model.addRow(new Object[]{
                        o.getOrderid(),
                        o.getPickDT(),
                        o.getTotal(),
                        o.getStatus()
                    });
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
