/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.views;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.pos.db.DBConnection;

/**
 *
 * @author Yashitha Nadiranga
 */
public class Main extends javax.swing.JFrame {

    int mouseX;
    int mouseY;
    
    public Main() {
        initComponents();
        loadConnection();
        loadHome();
        dateTime();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new javax.swing.JPanel();
        pnlleft = new javax.swing.JPanel();
        btnHome = new keeptoo.KButton();
        btnCollection = new keeptoo.KButton();
        btnOrders = new keeptoo.KButton();
        btnDelevery = new keeptoo.KButton();
        btnPayment = new keeptoo.KButton();
        btnCoustomer = new keeptoo.KButton();
        pnltop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        pnlload = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlmain.setBackground(new java.awt.Color(184, 14, 61));
        pnlmain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlmainMouseDragged(evt);
            }
        });
        pnlmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlmainMousePressed(evt);
            }
        });
        pnlmain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlleft.setBackground(new java.awt.Color(46, 42, 44));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_home_30px.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnHome.setIconTextGap(50);
        btnHome.setkAllowGradient(false);
        btnHome.setkAllowTab(true);
        btnHome.setkBackGroundColor(new java.awt.Color(46, 42, 44));
        btnHome.setkBorderRadius(0);
        btnHome.setkHoverColor(new java.awt.Color(55, 51, 53));
        btnHome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnHome.setkIndicatorColor(new java.awt.Color(184, 14, 61));
        btnHome.setkIndicatorThickness(6);
        btnHome.setkPressedColor(new java.awt.Color(46, 42, 44));
        btnHome.setkSelectedColor(new java.awt.Color(55, 51, 53));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCollection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_list_30px.png"))); // NOI18N
        btnCollection.setText("Collection");
        btnCollection.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnCollection.setIconTextGap(50);
        btnCollection.setkAllowGradient(false);
        btnCollection.setkAllowTab(true);
        btnCollection.setkBackGroundColor(new java.awt.Color(46, 42, 44));
        btnCollection.setkBorderRadius(0);
        btnCollection.setkHoverColor(new java.awt.Color(55, 51, 53));
        btnCollection.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnCollection.setkIndicatorColor(new java.awt.Color(184, 14, 61));
        btnCollection.setkIndicatorThickness(6);
        btnCollection.setkPressedColor(new java.awt.Color(46, 42, 44));
        btnCollection.setkSelectedColor(new java.awt.Color(55, 51, 53));
        btnCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectionActionPerformed(evt);
            }
        });

        btnOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_shopping_cart_30px.png"))); // NOI18N
        btnOrders.setText("Orders");
        btnOrders.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnOrders.setIconTextGap(50);
        btnOrders.setkAllowGradient(false);
        btnOrders.setkAllowTab(true);
        btnOrders.setkBackGroundColor(new java.awt.Color(46, 42, 44));
        btnOrders.setkBorderRadius(0);
        btnOrders.setkHoverColor(new java.awt.Color(55, 51, 53));
        btnOrders.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnOrders.setkIndicatorColor(new java.awt.Color(184, 14, 61));
        btnOrders.setkIndicatorThickness(6);
        btnOrders.setkPressedColor(new java.awt.Color(46, 42, 44));
        btnOrders.setkSelectedColor(new java.awt.Color(55, 51, 53));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        btnDelevery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_delivery_30px.png"))); // NOI18N
        btnDelevery.setText("Delevery");
        btnDelevery.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnDelevery.setIconTextGap(50);
        btnDelevery.setkAllowGradient(false);
        btnDelevery.setkAllowTab(true);
        btnDelevery.setkBackGroundColor(new java.awt.Color(46, 42, 44));
        btnDelevery.setkBorderRadius(0);
        btnDelevery.setkHoverColor(new java.awt.Color(55, 51, 53));
        btnDelevery.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDelevery.setkIndicatorColor(new java.awt.Color(184, 14, 61));
        btnDelevery.setkIndicatorThickness(6);
        btnDelevery.setkPressedColor(new java.awt.Color(46, 42, 44));
        btnDelevery.setkSelectedColor(new java.awt.Color(55, 51, 53));

        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_money_30px.png"))); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnPayment.setIconTextGap(50);
        btnPayment.setkAllowGradient(false);
        btnPayment.setkAllowTab(true);
        btnPayment.setkBackGroundColor(new java.awt.Color(46, 42, 44));
        btnPayment.setkBorderRadius(0);
        btnPayment.setkHoverColor(new java.awt.Color(55, 51, 53));
        btnPayment.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnPayment.setkIndicatorColor(new java.awt.Color(184, 14, 61));
        btnPayment.setkIndicatorThickness(6);
        btnPayment.setkPressedColor(new java.awt.Color(46, 42, 44));
        btnPayment.setkSelectedColor(new java.awt.Color(55, 51, 53));

        btnCoustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_customer_30px.png"))); // NOI18N
        btnCoustomer.setText("Customer");
        btnCoustomer.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnCoustomer.setIconTextGap(50);
        btnCoustomer.setkAllowGradient(false);
        btnCoustomer.setkAllowTab(true);
        btnCoustomer.setkBackGroundColor(new java.awt.Color(46, 42, 44));
        btnCoustomer.setkBorderRadius(0);
        btnCoustomer.setkHoverColor(new java.awt.Color(55, 51, 53));
        btnCoustomer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnCoustomer.setkIndicatorColor(new java.awt.Color(184, 14, 61));
        btnCoustomer.setkIndicatorThickness(6);
        btnCoustomer.setkPressedColor(new java.awt.Color(46, 42, 44));
        btnCoustomer.setkSelectedColor(new java.awt.Color(55, 51, 53));
        btnCoustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlleftLayout = new javax.swing.GroupLayout(pnlleft);
        pnlleft.setLayout(pnlleftLayout);
        pnlleftLayout.setHorizontalGroup(
            pnlleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addComponent(btnCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDelevery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCoustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlleftLayout.setVerticalGroup(
            pnlleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlleftLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelevery, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCoustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pnlmain.add(pnlleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 770));

        pnltop.setBackground(new java.awt.Color(255, 255, 255));
        pnltop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(184, 14, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_kawaii_french_fries_99px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kitchen");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Shirley's");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        pnltop.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, 128, 167));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_settings_30px.png"))); // NOI18N
        pnltop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 24, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_shutdown_30px_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        pnltop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 24, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/views/img/icons8_bell_30px.png"))); // NOI18N
        pnltop.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 24, -1, -1));

        lbldate.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        lbldate.setText("Date Time");
        pnltop.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        pnlmain.add(pnltop, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 990, 180));

        pnlload.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlloadLayout = new javax.swing.GroupLayout(pnlload);
        pnlload.setLayout(pnlloadLayout);
        pnlloadLayout.setHorizontalGroup(
            pnlloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        pnlloadLayout.setVerticalGroup(
            pnlloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pnlmain.add(pnlload, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 990, 570));

        getContentPane().add(pnlmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlmainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlmainMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X - mouseX, Y - mouseY);
    }//GEN-LAST:event_pnlmainMouseDragged

    private void pnlmainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlmainMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_pnlmainMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectionActionPerformed
        pnlload.removeAll();
        pnlmain.repaint();
        pnlload.add(new CollectionForm()).setVisible(true);
    }//GEN-LAST:event_btnCollectionActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        pnlload.removeAll();
        pnlmain.repaint();
        pnlload.add(new HomeForm()).setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        pnlload.removeAll();
        pnlmain.repaint();
        pnlload.add(new OrderForm()).setVisible(true);
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnCoustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoustomerActionPerformed
        pnlload.removeAll();
        pnlmain.repaint();
        pnlload.add(new CustomerForm()).setVisible(true);
    }//GEN-LAST:event_btnCoustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnCollection;
    private keeptoo.KButton btnCoustomer;
    private keeptoo.KButton btnDelevery;
    private keeptoo.KButton btnHome;
    private keeptoo.KButton btnOrders;
    private keeptoo.KButton btnPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JPanel pnlleft;
    private javax.swing.JPanel pnlload;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JPanel pnltop;
    // End of variables declaration//GEN-END:variables

    private void loadHome() {
        pnlload.removeAll();
        pnlload.repaint();
        pnlload.add(new HomeForm()).setVisible(true);
    }

    private void loadConnection(){
        try {
            DBConnection.getInstance().getConnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        private void dateTime() {
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                lbldate.setText(now.toLocalDate().toString() + "   " + now.getHour() + ":" + now.getMinute() + ":" + now.getSecond());
            }
        }, 0, 1000);
    }
}
